name: Build and Push Docker Image
env:
    APP_NAME: mywebsite
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    TAG: ${{ github.sha }}
    LATEST: v1.0/latest
on:
    push:
        paths:
            - '**'
            - '.github/workflows/**'
        branches:
            - main # trigger when you push to main branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # 1. Get your code
            - name: Checkout code
              uses: actions/checkout@v4

            # 2. Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKER_USERNAME }}
                  password: ${{ env.DOCKER_PASSWORD }}

            # 3. Build Docker image
            - name: Build image
              run: |
                  docker build -t ${{env.DOCKER_USERNAME}}/${{env.APP_NAME}}:${{ env.LATEST }} \
                  -t ${{env.DOCKER_USERNAME}}/${{env.APP_NAME}}:${{ env.TAG }} .

            # 4. Push to Docker Hub
            - name: Push image
              run: docker push ${{env.DOCKER_USERNAME}}/${{env.APP_NAME}}:${{ env.LATEST }}

            # - name: Deploy to Kubernetes
            #   run: |
            #    kubectl apply -f k8s/